const modules=[
['Pensar antes da IA','Mudar a relação com a IA e aprender a decidir seu papel.',1,3],
['Preparar o trabalho','Transformar pedidos vagos em tarefas claras.',4,5],
['Direcionar a IA','Fornecer contexto e instruções com propósito.',6,8],
['Avaliar e verificar','Aprender a julgar, encontrar problemas e verificar.',9,12],
['Refinar','Melhorar com feedback e saber quando parar.',13,14],
['Usar com responsabilidade','Trabalhar com dados, autoria e documentação.',15,17],
['Escolher estratégias e ferramentas','Escolher ferramentas e montar um fluxo próprio.',18,19],
['Projeto final','Provar transferência para uma tarefa nova.',20,20]
];
const titles=[
'IA como ferramenta de trabalho','Capacidades, limites e confiabilidade','Quando usar, quando não usar e quando supervisionar','Definindo uma tarefa profissional','Briefing proporcional e critérios de sucesso','Contexto: o que fornecer e como organizar','Anatomia de uma instrução profissional','Exemplos, referências e restrições','Uma resposta boa não é necessariamente uma resposta correta','Como avaliar uma saída de IA','Como encontrar erros e alucinações','Verificação: fontes, evidências e confiança','Iteração inteligente: feedback que realmente melhora','Melhorar, mudar de estratégia ou parar','Privacidade e dados: o que você pode compartilhar','IA, autoria e propriedade intelectual','Responsabilidade e documentação profissional','Como escolher a ferramenta certa','Construindo seu fluxo profissional de IA','Projeto final: do problema à entrega'];
const objectives=[
'Identificar onde a IA pode ajudar em uma tarefa e o que continua sendo responsabilidade humana.','Distinguir uma resposta útil de uma resposta que precisa de verificação.','Decidir o papel adequado da IA considerando benefício, risco, consequência e supervisão.','Transformar um pedido vago em uma tarefa com objetivo, público, escopo, formato e restrições.','Preparar um briefing proporcional e definir critérios de sucesso antes da execução.','Selecionar, organizar e priorizar o contexto realmente necessário.','Construir instruções claras conectando tarefa, contexto, critérios e formato.','Usar exemplos e referências para reduzir ambiguidades sem criar cópia mecânica.','Separar aparência profissional de qualidade e correção reais.','Avaliar uma saída usando o RACCCA como ferramenta didática.','Encontrar afirmações que merecem verificação e reconhecer sinais de possível erro.','Verificar informações importantes usando fontes e evidências adequadas.','Dar feedback específico que produza uma próxima versão melhor.','Decidir entre melhorar, mudar de estratégia ou parar.','Reconhecer dados que exigem cuidado e reduzir exposição desnecessária.','Entender princípios de autoria, terceiros, termos e diferenças de jurisdição sem transformar isso em aula jurídica.','Registrar decisões, verificações e alterações de forma proporcional.','Escolher ferramentas pelo trabalho, não pelo hype.','Integrar o método em um fluxo profissional reutilizável.','Aplicar o método inteiro em uma tarefa nova e demonstrar julgamento, processo e resultado.'
];
const challenges=[
'“Preciso de um post para minha academia. Faz aí.” O que você faria antes de simplesmente mandar a IA escrever?','Qual das três respostas você confiaria imediatamente: a mais bonita, a com erro óbvio ou a que parece correta mas tem um detalhe falso?','Você usaria IA da mesma maneira para resumir um texto e apoiar uma decisão importante?','“Crie um anúncio para minha academia.” O que falta para isso virar uma tarefa executável?','Uma legenda simples e uma campanha de lançamento precisam do mesmo briefing?','Você tem vinte informações sobre uma empresa, mas só cinco são relevantes para a tarefa. Enviaria tudo?','Compare “Faça um post para academia” com uma instrução que define objetivo, público, contexto e critérios. O que muda?','Se você quer determinado estilo, basta dizer “seja profissional”? O que uma referência acrescentaria?','Você recebeu um texto elegante e convincente. Antes de entregar, o que precisa perguntar?','Uma resposta pode ser correta e ainda inadequada? Pode ser clara e incompleta?','O que você verificaria primeiro: uma opinião, uma data específica ou um número exato?','A IA citou um site. Isso sozinho prova a afirmação?','“Melhore esse texto.” O que a IA sabe exatamente sobre o que melhorar?','Você fez quatro versões e cada uma muda pouco. Continuar sempre é melhor?','Você recebeu um documento de cliente e quer pedir à IA para resumi-lo. Colocaria tudo no chat sem pensar?','Se a IA ajudou a criar algo, isso significa automaticamente que você pode usar qualquer parte dele?','Se a IA participou de um trabalho importante, o que você gostaria de conseguir explicar depois?','A ferramenta mais famosa é automaticamente a melhor para sua tarefa?','Se você tivesse que ensinar outra pessoa a realizar uma tarefa com IA com qualidade, quais etapas ela deveria seguir?','Escolha uma tarefa nova, diferente dos exemplos, e resolva o problema usando o método inteiro.'
];
const errors=[
'Começar pelo prompt e aceitar a primeira resposta. Em tarefas simples isso pode bastar; em trabalhos importantes, faltam definição e julgamento.','Confundir texto convincente com verdade. Fluência não é evidência.','Usar uma regra absoluta: IA resolve tudo ou IA não serve. O papel deve ser proporcional ao risco.','Tentar compensar uma tarefa mal definida com um prompt enorme.','Tratar briefing como burocracia ou despejar informação sem saber o que importa.','Colocar todo o contexto “para garantir”, mesmo quando é irrelevante, confuso ou contraditório.','Acreditar em prompt mágico em vez de clareza, contexto e critérios.','Usar referências sem explicar a função delas ou pedir cópia direta.','Confundir texto bonito com trabalho correto.','Avaliar apenas por “gostei/não gostei”.','Verificar tudo da mesma forma ou não verificar nada.','Tratar qualquer link como prova suficiente.','Fazer várias rodadas sem objetivo esperando que a IA descubra o problema.','Confundir mais iterações com mais qualidade.','Compartilhar dados porque “é só com a IA”, sem necessidade ou cuidado.','Tratar “foi feito por IA” como resposta universal para direitos e autoria.','Guardar só a resposta final e perder decisões e verificações importantes.','Escolher pelo hype, marca ou quantidade de recursos.','Ter bons prompts isolados sem um processo completo.','Fazer um prompt bonito e chamar isso de projeto concluído.'
];
const takeaways=[
'Comece pelo problema, não pelo prompt. IA é ferramenta, não autoridade.','Fluência não é evidência. Quanto maior a consequência, maior o cuidado.','Uso profissional é saber quando usar, para quê e quanto supervisionar.','Antes de pedir melhor, defina melhor o trabalho.','Briefing é redução de ambiguidade na medida certa.','Contexto bom é útil, organizado e suficiente — não máximo.','Prompt é instrução; clareza, contexto e critérios importam mais que magia.','Exemplo bom reduz ambiguidade; referência sem propósito aumenta ruído.','Pergunte se está bom para a finalidade, não apenas se ficou bonito.','Critérios transformam “gostei” em avaliação.','Afirmações importantes devem ter um caminho de verificação.','Confiança vem de evidência adequada à decisão.','Cada rodada precisa de uma razão clara.','Iterar profissionalmente também é saber parar.','Pergunte não só “a IA consegue usar?”, mas “ela precisa receber isso?”.','Questões de autoria dependem de contexto, termos e jurisdição; não há frase universal.','Documentação proporcional torna o trabalho explicável e revisável.','Não existe “melhor IA” universal; existe ferramenta adequada à tarefa.','Profissionalismo aparece no fluxo inteiro, não apenas no prompt.','Você terminou quando consegue trabalhar com IA com critério, não apenas pedir.'
];
const learn=[
['Ver IA como ferramenta de trabalho.','Separar apoio da IA de decisão humana.','Perceber que resposta pronta não é entrega pronta.'],['Reconhecer capacidades comuns.','Separar qualidade de escrita de verdade.','Relacionar risco à verificação.'],['Identificar benefício.','Reconhecer necessidade de supervisão.','Evitar regras absolutas.'],['Distinguir pedido de tarefa.','Definir objetivo e escopo.','Explicitar requisitos.'],['Escolher nível de preparação.','Definir critérios observáveis.','Evitar excesso de briefing.'],['Separar relevante de irrelevante.','Priorizar informações.','Organizar contexto.'],['Conhecer elementos de uma boa instrução.','Usar critérios e formato.','Evitar fórmulas rígidas.'],['Saber quando exemplos ajudam.','Usar referências com função clara.','Definir restrições necessárias.'],['Separar aparência de qualidade real.','Encontrar problemas específicos.','Perguntar se entregaria.'],['Aplicar Relevância, Acurácia, Clareza, Completude, Concisão e Adequação.'],['Localizar afirmações verificáveis.','Prestar atenção a datas, números e nomes.','Priorizar pelo risco.'],['Distinguir fonte de evidência.','Comparar fontes quando necessário.','Registrar incerteza.'],['Identificar problema.','Definir mudança.','Criar critério para a próxima versão.'],['Reconhecer ganho real.','Detectar repetição.','Parar quando critérios são atendidos.'],['Diferenciar dados comuns, pessoais, sensíveis e confidenciais.','Reduzir exposição.','Considerar regras da ferramenta.'],['Considerar participação humana e conteúdo de terceiros.','Perceber diferenças de jurisdição.','Saber quando buscar orientação especializada.'],['Registrar decisões importantes.','Registrar verificações.','Manter documentação proporcional.'],['Comparar capacidade, qualidade, contexto, velocidade, custo e limitações.'],['Conectar decidir, preparar, direcionar, executar, avaliar, verificar, refinar, controlar e entregar.'],['Demonstrar precisão, completude, adequação, eficiência, julgamento e documentação.']
];
const phases=['DECIDIR','DECIDIR','DECIDIR','PREPARAR','PREPARAR','DIRECIONAR','DIRECIONAR','DIRECIONAR','AVALIAR','AVALIAR','AVALIAR','AVALIAR','REFINAR','REFINAR','CONTROLAR','CONTROLAR','CONTROLAR','INTEGRAR','INTEGRAR','DEMONSTRAR'];
const KEY='upia-v02-fix-progress';let state=JSON.parse(localStorage.getItem(KEY)||'{}');
const app=document.getElementById('app');
function save(){localStorage.setItem(KEY,JSON.stringify(state))}function done(n){return !!state['a'+n]}function percent(){return Math.round(Object.keys(state).length/20*100)}
function header(){return `<header class="top"><div class="brand"><button class="btn mobile" onclick="toggleSide()">☰</button><span class="mark">IA</span><span>Uso Profissional de IA <small style="color:var(--muted)">V0.2</small></span></div><div class="top-right"><span class="pct">${Object.keys(state).length}/20</span><div class="bar"><span style="width:${percent()}%"></span></div><b>${percent()}%</b></div></header>`}
function sidebar(){return `<aside class="side" id="side"><div class="side-title">Curso</div><button class="navbtn" onclick="go('#/')">⌂ Início</button><button class="navbtn" onclick="go('#/curso')">▣ 20 aulas</button><button class="navbtn" onclick="go('#/validacao')">✓ Plano de validação</button><div class="side-title">Módulos</div>${modules.map((m,i)=>`<button class="navbtn" onclick="go('#/modulo/${i+1}')">${String(i+1).padStart(2,'0')} · ${m[0]}</button>`).join('')}</aside>`}
function lessonLink(n){return `<a class="lesson" href="#/aula/${n}"><span class="num">${String(n).padStart(2,'0')}</span><div><h4>${titles[n-1]}</h4><small>${phases[n-1]} · ${objectives[n-1]}</small></div><span class="state">${done(n)?'✓':'→'}</span></a>`}
function home(){app.innerHTML=`${header()}<div class="layout">${sidebar()}<main><div class="content"><section class="hero"><span class="eyebrow">CURSO 01 · TRILHA PROFISSIONAL · V0.2</span><h1>Não é sobre pedir melhor.<br><span class="gradient">É sobre trabalhar melhor com IA.</span></h1><p>Aprenda a decidir, preparar, direcionar, avaliar, verificar, refinar e entregar trabalhos com IA — sem depender de “prompt mágico”.</p><div class="actions"><a class="btn primary" href="#/aula/${Object.keys(state).length?Math.min(20,Object.keys(state).length+1):1}">${Object.keys(state).length?'Continuar curso':'Começar Aula 01'}</a><a class="btn ghost" href="#/validacao">Plano de validação</a></div></section><div class="stats"><div class="stat"><strong>20</strong><small>aulas</small></div><div class="stat"><strong>8</strong><small>módulos</small></div><div class="stat"><strong>6</strong><small>fases do método</small></div><div class="stat"><strong>${percent()}%</strong><small>progresso</small></div></div><div class="section-head"><span class="eyebrow">Jornada</span><h2>4 níveis + desafio final</h2></div><div class="modules">${[['Nível 1','Usuário comum','Aulas 01–03'],['Nível 2','Usuário estruturado','Aulas 04–08'],['Nível 3','Usuário crítico','Aulas 09–14'],['Nível 4','Usuário profissional','Aulas 15–19'],['★','Desafio final','Aula 20']].map(x=>`<div class="module"><span class="tag">${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p></div>`).join('')}</div><div class="section-head"><span class="eyebrow">Trilha completa</span><h2>20 aulas arquitetadas</h2></div><div class="lesson-list">${titles.map((_,i)=>lessonLink(i+1)).join('')}</div></div></main></div><div class="toast" id="toast"></div>`}
function course(){app.innerHTML=`${header()}<div class="layout">${sidebar()}<main><div class="content"><div class="page-head"><span class="eyebrow">TRILHA COMPLETA</span><h1>20 aulas arquitetadas</h1><p>Abra qualquer aula. O conteúdo foi organizado para aprender → ver → fazer → conferir → aplicar.</p></div>${modules.map((m,i)=>`<section class="module"><span class="tag">MÓDULO ${String(i+1).padStart(2,'0')}</span><h3>${m[0]}</h3><p>${m[1]}</p><div class="lesson-list">${Array.from({length:m[3]-m[2]+1},(_,j)=>lessonLink(m[2]+j)).join('')}</div></section>`).join('<div style="height:12px"></div>')}</div></main></div><div class="toast" id="toast"></div>`}
function modulePage(no){let m=modules[no-1];app.innerHTML=`${header()}<div class="layout">${sidebar()}<main><div class="content"><div class="page-head"><span class="eyebrow">MÓDULO ${String(no).padStart(2,'0')}</span><h1>${m[0]}</h1><p>${m[1]}</p></div><div class="lesson-list">${Array.from({length:m[3]-m[2]+1},(_,j)=>lessonLink(m[2]+j)).join('')}</div></div></main></div><div class="toast" id="toast"></div>`}
function lesson(n){let i=n-1;app.innerHTML=`${header()}<div class="layout">${sidebar()}<main><div class="content"><div class="page-head"><span class="eyebrow">AULA ${String(n).padStart(2,'0')} · ${phases[i]}</span><h1>${titles[i]}</h1><p>${objectives[i]}</p></div><div class="video"><div><div class="play">▶</div><p>Audiovisual preparado para esta aula</p><small>Na V0.2, o espaço está pronto. O recurso definitivo será produzido depois da validação pedagógica.</small></div></div><div class="blocks"><section class="block"><span class="tag">🎯 OBJETIVO</span><h3>O que você precisa conseguir fazer</h3><p>${objectives[i]}</p></section><section class="block"><span class="tag">🧠 APRENDER</span><h3>Competências</h3><ul>${learn[i].map(x=>`<li>${x}</li>`).join('')}</ul></section><section class="block full"><span class="tag">⚡ DESAFIO INICIAL</span><h3>Pense antes da explicação</h3><p>${challenges[i]}</p></section><section class="block"><span class="tag">❌ ERRO COMUM</span><h3>O comportamento que vamos corrigir</h3><p>${errors[i]}</p></section><section class="block"><span class="tag">💡 CONCEITO</span><h3>A ideia central</h3><p>${takeaways[i]}</p></section><section class="block full"><span class="tag">👀 DEMONSTRAÇÃO</span><h3>Veja o princípio funcionando</h3><p>Compare uma abordagem casual com uma abordagem profissional. Observe o que muda na definição da tarefa, na orientação dada à IA e na qualidade do resultado.</p></section><section class="block full practice"><span class="tag">🛠️ PRÁTICA</span><h3>Agora é você</h3><p>Execute a competência desta aula em uma tarefa real ou fictícia. Não procure fazer “perfeito” de primeira: faça, observe o resultado e use os critérios da conferência.</p></section><section class="block"><span class="tag">✅ CONFERÊNCIA</span><h3>Antes de avançar</h3><ul class="check"><li>Consigo explicar a ideia com minhas palavras.</li><li>Consigo executar a tarefa sem copiar o exemplo.</li><li>Consigo apontar um problema ou critério de qualidade.</li><li>Consigo dizer o que faria em outro contexto.</li></ul></section><section class="block"><span class="tag">🔄 APLICAÇÃO</span><h3>Transfira para outro contexto</h3><p>Escolha uma situação diferente da demonstração e aplique a mesma competência. O objetivo é provar que você aprendeu o princípio, não decorou o exemplo.</p></section><section class="block full"><span class="tag">📌 O QUE LEVAR</span><h3>${takeaways[i]}</h3></section></div><div class="navrow"><a class="btn ghost" href="${n>1?'#/aula/'+(n-1):'#/curso'}">← ${n>1?'Aula anterior':'Voltar à trilha'}</a><button class="btn primary" onclick="toggleDone(${n})">${done(n)?'✓ Concluída · desmarcar':'Marcar como concluída'}</button><a class="btn primary" href="${n<20?'#/aula/'+(n+1):'#/validacao'}">${n<20?'Próxima aula →':'Concluir →'}</a></div></div></main></div><div class="toast" id="toast"></div>`}
function validation(){app.innerHTML=`${header()}<div class="layout">${sidebar()}<main><div class="content"><div class="page-head"><span class="eyebrow">VALIDAÇÃO</span><h1>Primeiro provamos que ensina.</h1><p>V0.2 é uma versão funcional para demonstração e teste. A aparência não substitui a validação da aprendizagem.</p></div><div class="validation"><div class="notice"><h3>01 · Auditar as 20 aulas</h3><p>Verificar competência central, objetivo ↔ prática, transições, repetição, lacunas, dificuldade e transferência.</p></div><div class="notice"><h3>02 · Testar com iniciante</h3><p>Uma pessoa por vez, sem explicação particular antes. Observar se entende, executa, explica e transfere.</p></div><div class="notice"><h3>03 · Corrigir com evidência</h3><p>Falha observada → hipótese da causa → alteração → novo teste. Não mudar apenas por gosto estético.</p></div><div class="notice"><h3>04 · Produzir audiovisual</h3><p>Depois do teste, decidir onde vídeo, gravação de tela, imagem, mapa ou animação realmente melhora a aprendizagem.</p></div><div class="notice practice"><h3>Regra do projeto</h3><p><strong>Se o conceito não funciona sem efeitos, efeitos não vão salvá-lo.</strong> O audiovisual deve amplificar uma aula que já ensina.</p></div></div></div></main></div><div class="toast" id="toast"></div>`}
function toggleDone(n){if(done(n))delete state['a'+n];else state['a'+n]=true;save();render();toast(done(n)?'Aula marcada como concluída.':'Aula desmarcada.')}function toast(msg){let t=document.getElementById('toast');if(t){t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1600)}}function toggleSide(){document.getElementById('side')?.classList.toggle('open')}
function go(h){location.hash=h}
function render(){let h=location.hash||'#/' ;if(h==='#/'||h==='#')home();else if(h==='#/curso')course();else if(h==='#/validacao')validation();else{let a=h.match(/^#\/aula\/(\d+)$/),m=h.match(/^#\/modulo\/(\d+)$/);if(a&&+a[1]>=1&&+a[1]<=20)lesson(+a[1]);else if(m&&+m[1]>=1&&+m[1]<=8)modulePage(+m[1]);else home()}window.scrollTo(0,0)}
window.addEventListener('hashchange',render);window.toggleDone=toggleDone;window.toggleSide=toggleSide;window.go=go;render();
