const COURSE={title:'Uso Profissional de IA',version:'V0.2',modules:[
{id:1,title:'Pensar antes da IA',goal:'Mudar a relação com a IA: entender capacidades, limites e responsabilidade.',lessons:[
['IA como ferramenta de trabalho','Identificar onde a IA pode apoiar uma tarefa e o que continua sendo responsabilidade humana.'],['Capacidades, limites e confiabilidade','Distinguir capacidade útil de confiabilidade e reconhecer quando uma saída precisa de verificação.'],['Quando usar, quando não usar e quando supervisionar','Decidir o papel adequado da IA conforme benefício, risco, consequência e possibilidade de verificação.']]},
{id:2,title:'Preparar o trabalho',goal:'Pensar na tarefa antes de abrir o chat.',lessons:[
['Definindo uma tarefa profissional','Transformar um pedido vago em um trabalho claramente definido.'],['Briefing proporcional e critérios de sucesso','Definir quanto planejamento uma tarefa precisa e como reconhecer um bom resultado.']]},
{id:3,title:'Direcionar a IA',goal:'Transformar pensamento estruturado em orientação eficaz.',lessons:[
['Contexto: o que fornecer e como organizar','Selecionar, priorizar e organizar informação relevante sem confundir contexto com quantidade.'],['Anatomia de uma instrução profissional','Construir orientações claras e proporcionais à tarefa.'],['Exemplos, referências e restrições','Usar referências para reduzir ambiguidades sem criar ruído ou confundir referência com cópia.']]},
{id:4,title:'Avaliar e verificar',goal:'Deixar de ser alguém que apenas copia a resposta.',lessons:[
['Uma resposta boa não é necessariamente uma resposta correta','Separar qualidade aparente de confiabilidade.'],['Como avaliar uma saída de IA','Aplicar o RACCCA como ferramenta didática de avaliação.'],['Como encontrar erros e alucinações','Identificar afirmações que merecem investigação e sinais de alerta.'],['Verificação: fontes, evidências e confiança','Verificar informações importantes com fontes adequadas e comunicar incerteza quando necessário.']]},
{id:5,title:'Refinar',goal:'Melhorar resultados sem ciclos intermináveis.',lessons:[
['Iteração inteligente: feedback que realmente melhora','Transformar “não gostei” em feedback específico e acionável.'],['Melhorar, mudar de estratégia ou parar','Decidir se a próxima ação deve ser refinar, mudar a abordagem ou encerrar.']]},
{id:6,title:'Usar com responsabilidade',goal:'Reconhecer riscos de dados, conteúdo e responsabilidade sem transformar o curso em consultoria jurídica.',lessons:[
['Privacidade e dados: o que você pode compartilhar','Identificar dados que exigem cuidado e reduzir exposição desnecessária.'],['IA, autoria e propriedade intelectual','Reconhecer questões de autoria, conteúdo de terceiros, termos e diferenças de jurisdição sem dar respostas jurídicas universais.'],['Responsabilidade e documentação profissional','Manter controle humano sobre o resultado e registrar decisões importantes de forma proporcional.']]},
{id:7,title:'Escolher estratégias e ferramentas',goal:'Escolher ferramentas pelo problema, não pelo hype.',lessons:[
['Como escolher a ferramenta certa','Escolher ferramentas de acordo com tarefa, requisitos, limitações e contexto.'],['Construindo seu fluxo profissional de IA','Montar um fluxo reutilizável do problema à entrega.']]},
{id:8,title:'Projeto final',goal:'Provar competência aplicando o método em uma tarefa nova.',lessons:[
['Projeto final: do problema à entrega','Conduzir uma tarefa completa e demonstrar julgamento, processo e resultado.']]}
]};
const ARCH=[
['Objetivo','A competência observável que o aluno precisa desenvolver.'],['Desafio inicial','Uma situação que faz o aluno pensar antes da explicação.'],['O erro comum','O comportamento casual que a aula pretende corrigir.'],['Conceito','A ideia central, ensinada de forma simples e proporcional.'],['Demonstração','Ver o conceito funcionando em uma situação realista.'],['Prática','O aluno executa a competência por conta própria.'],['Conferência','Critérios objetivos para o aluno verificar o próprio trabalho.'],['Aplicação','Uma situação diferente para testar transferência.'],['O que levar','A ideia reutilizável que deve permanecer depois da aula.']];
const KEY='upia-v02-progress';let state=JSON.parse(localStorage.getItem(KEY)||'{}');const app=document.getElementById('app'),nav=document.getElementById('courseNav');const total=20;
const phaseNames=['DECIDIR','DECIDIR','DECIDIR','PREPARAR','PREPARAR','DIRECIONAR','DIRECIONAR','DIRECIONAR','AVALIAR','AVALIAR','AVALIAR','AVALIAR','REFINAR','REFINAR','CONTROLAR','CONTROLAR','CONTROLAR','INTEGRAR','INTEGRAR','DEMONSTRAR'];
function lid(mi,li){return `${COURSE.modules[mi].id}-${li+1}`}function flat(){return COURSE.modules.flatMap((m,mi)=>m.lessons.map((l,li)=>({mi,li,id:lid(mi,li),module:m,lesson:l})))}function count(){return Object.values(state).filter(Boolean).length}function save(){localStorage.setItem(KEY,JSON.stringify(state));progress()}function progress(){let p=Math.round(count()/total*100);document.getElementById('topProgressBar').style.width=p+'%';document.getElementById('topProgressText').textContent=p+'%'}
function buildNav(){nav.innerHTML=COURSE.modules.map((m,mi)=>{let d=m.lessons.filter((_,li)=>state[lid(mi,li)]).length;return `<div class="module-nav ${location.hash.includes('/m'+m.id)?'open':''}"><button class="module-toggle" onclick="toggleModule(this)"><span class="module-number">${String(m.id).padStart(2,'0')}</span><span class="module-title">${m.title}</span><span class="module-count">${d}/${m.lessons.length}</span><span class="chev">›</span></button><div class="lesson-list">${m.lessons.map((l,li)=>`<a class="lesson-link ${location.hash===`#/m${m.id}/a${li+1}`?'active':''}" href="#/m${m.id}/a${li+1}"><span class="lesson-state">${state[lid(mi,li)]?'✓':'○'}</span><span>Aula ${String(li+1).padStart(2,'0')} · ${l[0]}</span></a>`).join('')}</div></div>`}).join('')}
window.toggleModule=e=>e.parentElement.classList.toggle('open');
function home(){app.innerHTML=`<section class="hero"><div><span class="kicker">Curso 01 · Arquitetura V0.2</span><h1>Não é sobre pedir melhor.<br><span class="gradient-text">É sobre trabalhar melhor com IA.</span></h1><p>As 20 aulas já estão estruturadas no ambiente. Agora vamos validar a pedagogia antes de investir na produção audiovisual definitiva.</p><div class="hero-actions"><a class="btn primary" href="#/curso">Abrir as 20 aulas →</a><a class="btn ghost" href="#/sobre">Plano de validação</a></div></div><div class="hero-visual"><div class="orbit"></div><div class="core">IA<br>como<br>ferramenta</div><span class="node n1">DECIDIR</span><span class="node n2">DIRECIONAR</span><span class="node n3">AVALIAR</span><span class="node n4">ENTREGAR</span></div></section><section><div class="section-title"><span class="kicker">Progressão</span><h2>4 níveis + desafio final</h2></div><div class="journey-grid"><div><b>01</b><strong>Usuário comum</strong><span>Aulas 01–03</span></div><div><b>02</b><strong>Usuário estruturado</strong><span>Aulas 04–08</span></div><div><b>03</b><strong>Usuário crítico</strong><span>Aulas 09–14</span></div><div><b>04</b><strong>Usuário profissional</strong><span>Aulas 15–19</span></div><div><b>★</b><strong>Desafio final</strong><span>Aula 20</span></div></div></section>`}
function dashboard(){app.innerHTML=`<div class="dashboard-head"><div><span class="kicker">Trilha completa</span><h1>20 aulas arquitetadas</h1><p>Cada aula agora possui espaço próprio para objetivo, desafio, erro comum, conceito, demonstração, prática, conferência, aplicação e síntese.</p></div><div class="overall"><strong>${Math.round(count()/total*100)}%</strong><small>progresso de navegação</small><div class="bar"><span style="width:${Math.round(count()/total*100)}%"></span></div></div></div>${COURSE.modules.map((m,mi)=>`<article class="module-card"><div class="module-card-head"><div class="module-index">${String(m.id).padStart(2,'0')}</div><div><h2>${m.title}</h2><p>${m.goal}</p></div><div class="module-pct">${m.lessons.filter((_,li)=>state[lid(mi,li)]).length}/${m.lessons.length}</div></div><div class="module-lessons">${m.lessons.map((l,li)=>`<a class="lesson-row" href="#/m${m.id}/a${li+1}"><span class="lesson-num">${String(li+1).padStart(2,'0')}</span><div><h3>${l[0]}</h3><small>${l[1]}</small></div><span class="go ${state[lid(mi,li)]?'done':''}">${state[lid(mi,li)]?'✓':'→'}</span></a>`).join('')}</div></article>`).join('')}`}
function about(){app.innerHTML=`<div class="lesson-page"><span class="kicker">Validação antes da produção</span><h1>Primeiro provamos que ensina.</h1><p class="lesson-intro">O próximo passo não é encher o curso de efeitos. É testar se uma pessoa iniciante absorve exatamente aquilo que colocamos na aula com propósito.</p><div class="content-block"><h2>01 · Auditoria das 20 aulas</h2><p>Revisaremos repetição, lacunas, saltos de dificuldade, excesso, exercícios, transições e alinhamento entre promessa e prática.</p></div><div class="content-block"><h2>02 · Teste com seu irmão ou amigo</h2><p>Um deles fará o percurso sem receber explicação particular antes. Vamos observar aprendizagem, execução, transferência, confusão, retenção e experiência.</p><div class="test-grid"><div><b>Aprendeu?</b><span>Consegue explicar com as próprias palavras?</span></div><div><b>Conseguiu fazer?</b><span>Executa a competência sem nossa mão?</span></div><div><b>Transferiu?</b><span>Aplica em outro contexto?</span></div><div><b>Entendeu errado?</b><span>Onde a aula permite interpretação equivocada?</span></div><div><b>Reteve?</b><span>O que permanece depois de um intervalo?</span></div><div><b>Experiência?</b><span>Onde o ritmo ou formato atrapalha?</span></div></div></div><div class="content-block"><h2>03 · Corrigir com evidência</h2><p>Falha observada → hipótese de causa → alteração → novo teste. Não vamos mudar uma aula só por preferência estética.</p></div><div class="content-block"><h2>04 · Preparar audiovisual</h2><p>Depois do teste decidiremos quais trechos merecem vídeo, imagem, mapa, animação, gravação de tela ou apenas texto. Cada recurso precisa ter uma função pedagógica.</p></div><div class="content-block exercise"><span class="tag">REGRA</span><h2>Se o conceito não funciona sem efeitos, efeitos não vão salvá-lo.</h2><p>O audiovisual deve amplificar uma aula que já ensina, não esconder uma aula que não ensina.</p></div></div>`}
function detail(mi,li){const m=COURSE.modules[mi],l=m.lessons[li],f=flat(),i=f.findIndex(x=>x.mi===mi&&x.li===li),prev=f[i-1],next=f[i+1],id=lid(mi,li),done=!!state[id];let phase=phaseNames[i];let purpose=[l[1],'Fazer o aluno pensar antes de receber a explicação e terminar com uma ação observável.','Corrigir o comportamento casual mais provável nesta competência.','Ensinar um princípio durável, sem depender de uma ferramenta específica.','Mostrar o princípio funcionando e tornar visível o raciocínio profissional.','Colocar o aluno para fazer, não apenas reconhecer.','Dar critérios para que ele confira o próprio trabalho.','Testar a mesma competência em um contexto diferente.','Deixar uma regra ou ferramenta que possa ser reutilizada.'];app.innerHTML=`<div class="lesson-page"><div class="lesson-meta"><span class="pill">Módulo ${String(m.id).padStart(2,'0')}</span><span>›</span><span>Aula ${String(li+1).padStart(2,'0')}</span><span class="lesson-phase">${phase}</span></div><h1>${l[0]}</h1><p class="lesson-intro">${l[1]}</p><div class="video-placeholder"><div class="video-grid"></div><div class="video-center"><div class="video-icon">▶</div><strong>Área audiovisual · pronta para produção</strong><small>Depois do teste pedagógico, este espaço receberá o recurso que realmente ajudar a aprender.</small></div></div><div class="content-grid"><div>${ARCH.map((a,j)=>`<section class="content-block lesson-section ${j===5?'exercise':''}"><span class="tag">${a[0].toUpperCase()}</span><h2>${a[0]}</h2><p>${purpose[j]}</p></section>`).join('')}<section class="content-block material"><span class="tag">📦 MATERIAL</span><h2>Material reutilizável da aula</h2><p>Checklist, mapa, template, guia ou rubrica será produzido a partir da necessidade observada no teste.</p></section></div><aside class="side-card"><div class="side-label">PROPÓSITO</div><h3>O que esta aula precisa mudar</h3><p>Não basta o aluno achar interessante. Precisamos observar uma mudança de entendimento ou comportamento.</p><div class="side-divider"></div><div class="side-label">STATUS</div><div class="status-big ${done?'done':''}'>${done?'✓ Marcada como concluída':'○ Em desenvolvimento'}</div><button class="btn primary check-btn" onclick="completeLesson('${id}')">${done?'Desmarcar':'Marcar como concluída'}</button><div class="completed-note">Marcador de navegação; a validação real será feita com iniciante.</div></aside></div><div class="lesson-nav">${prev?`<a class="btn ghost" href="#/m${prev.module.id}/a${prev.li+1}">← Anterior</a>`:`<a class="btn ghost" href="#/curso">← Módulos</a>`}${next?`<a class="btn primary" href="#/m${next.module.id}/a${next.li+1}">Próxima aula →</a>`:`<a class="btn primary" href="#/sobre">Próxima fase →</a>`}</div></div>`}
window.completeLesson=id=>{if(state[id])delete state[id];else state[id]=true;save();render()};function render(){buildNav();progress();let h=location.hash||'#/';if(h==='#/'||h==='#')home();else if(h==='#/curso')dashboard();else if(h==='#/sobre')about();else{let m=h.match(/^#\/m(\d+)\/a(\d+)$/);if(m){let mi=COURSE.modules.findIndex(x=>x.id==+m[1]),li=+m[2]-1;if(mi>=0&&li>=0&&li<COURSE.modules[mi].lessons.length)detail(mi,li);else home()}else home()}document.getElementById('app').focus({preventScroll:true})}document.getElementById('menuBtn').onclick=()=>document.getElementById('sidebar').classList.toggle('open');window.addEventListener('hashchange',()=>{document.getElementById('sidebar').classList.remove('open');render()});render();
